
import { useState, useEffect } from 'react';
import { UseFormReturn } from 'react-hook-form';
import { GroupFormValues } from '@/components/Groups/GroupInfoForm';
import { Participant, Category } from '../types';
import { generateGroupName } from '../utils/groupUtils';
import { useToast } from '@/hooks/use-toast';

interface UseGroupFormProps {
  form: UseFormReturn<GroupFormValues>;
  initialParticipants?: Participant[];
  mockParticipants: Participant[];
}

export const useGroupForm = ({ 
  form, 
  initialParticipants = [],
  mockParticipants
}: UseGroupFormProps) => {
  const { toast } = useToast();
  const [selectedParticipants, setSelectedParticipants] = useState<Participant[]>(initialParticipants);
  const [availableParticipants, setAvailableParticipants] = useState<Participant[]>([]);
  const [selectedCategory, setSelectedCategory] = useState<Category>(form.watch('category') as Category);
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true);

  // Get the current values from the form
  const { category, size } = form.watch();

  // Update available participants when category changes
  useEffect(() => {
    setSelectedCategory(category as Category);
    setSelectedParticipants([]); // Clear selected participants when category changes
    
    // Filter participants by category
    const filtered = mockParticipants.filter(
      (p) => p.category === category
    );
    setAvailableParticipants(filtered);
  }, [category, mockParticipants]);

  // Auto-generate group name when selected participants change
  useEffect(() => {
    if (isNameAutoGenerated && selectedParticipants.length > 0) {
      const generatedName = generateGroupName(selectedParticipants);
      form.setValue('name', generatedName);
    }
  }, [selectedParticipants, isNameAutoGenerated, form]);

  // Handle adding a participant to the group
  const addParticipant = (participant: Participant) => {
    // Check if we've reached the maximum number of participants for the selected size
    const maxParticipants = size === 'three' ? 3 : 4;
    if (selectedParticipants.length >= maxParticipants) {
      toast({
        title: "Maximale Anzahl erreicht",
        description: `Eine ${size === 'three' ? 'Dreier' : 'Vierer'}gruppe kann maximal ${maxParticipants} Teilnehmer haben.`,
        variant: "destructive"
      });
      return;
    }

    // Check if participant is already selected
    if (selectedParticipants.some(p => p.id === participant.id)) {
      toast({
        title: "Teilnehmer bereits ausgewählt",
        description: `${participant.firstName} ${participant.lastName} ist bereits in dieser Gruppe.`,
        variant: "destructive"
      });
      return;
    }

    const updatedSelectedParticipants = [...selectedParticipants, participant];
    setSelectedParticipants(updatedSelectedParticipants);
    
    // Update the name immediately if auto-generated
    if (isNameAutoGenerated) {
      const generatedName = generateGroupName(updatedSelectedParticipants);
      form.setValue('name', generatedName);
    }
    
    // No longer remove from available participants, just move to the bottom
    setAvailableParticipants([
      ...availableParticipants.filter(p => p.id !== participant.id),
      participant
    ]);
  };

  // Handle removing a participant from the group
  const removeParticipant = (participant: Participant) => {
    const updatedSelectedParticipants = selectedParticipants.filter(p => p.id !== participant.id);
    setSelectedParticipants(updatedSelectedParticipants);
    
    // Update the name immediately if auto-generated
    if (isNameAutoGenerated) {
      const generatedName = generateGroupName(updatedSelectedParticipants);
      form.setValue('name', generatedName);
    }
    
    // Move the participant to the top of available participants
    setAvailableParticipants([
      participant,
      ...availableParticipants.filter(p => p.id !== participant.id)
    ]);
  };

  // Handle name change
  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    form.setValue('name', e.target.value);
    setIsNameAutoGenerated(false);
  };

  // Regenerate name button handler
  const handleRegenerateName = () => {
    const generatedName = generateGroupName(selectedParticipants);
    form.setValue('name', generatedName);
    setIsNameAutoGenerated(true);
  };

  return {
    selectedParticipants,
    setSelectedParticipants,
    availableParticipants,
    selectedCategory,
    isNameAutoGenerated,
    addParticipant,
    removeParticipant,
    handleNameChange,
    handleRegenerateName
  };
};
